/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.plantarecicladora;

/**
 *
 * @author aubog
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    
    public Menu() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Planta Recicladora");

        jButton2.setText("Ver Residuo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Apilar Residuo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Trasladar  Residuo");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Ver Residuos");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Desencolar Residuos");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Convertir a productos reciclados ");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton1.setText("Empacar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(jButton7))
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addGap(68, 68, 68))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jLabel1))
                        .addGap(64, 64, 64)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addGap(56, 56, 56)
                .addComponent(jButton1)
                .addContainerGap(197, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Pila pila = new Pila();
        residuo residuo1 = new residuo("Botella", "Plastico");
        residuo residuo2 = new residuo("Caja", "Carton");
        residuo residuo3 = new residuo("Bolsa", "Plastico");
        residuo residuo4 = new residuo("Lata", "Alunimio");
        
        pila.apilar(residuo1);
        pila.apilar(residuo2);
        pila.apilar(residuo3);
        pila.apilar(residuo4);
        
        System.out.println("Se apilaron los residuos");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Pila pila = new Pila();
        residuo residuo1 = new residuo("Botella", "Plastico");
        residuo residuo2 = new residuo("Caja", "Carton");
        residuo residuo3 = new residuo("Bolsa", "Plastico");
        residuo residuo4 = new residuo("Lata", "Alunimio");
        
        pila.apilar(residuo1);
        pila.apilar(residuo2);
        pila.apilar(residuo3);
        pila.apilar(residuo4);
        
        System.out.println(pila.imprimirPila());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Pila pila = new Pila();
        Cola cola = new Cola();
        
        residuo residuo1 = new residuo("Botella", "Plastico");
        residuo residuo2 = new residuo("Caja", "Carton");
        residuo residuo3 = new residuo("Bolsa", "Plastico");
        residuo residuo4 = new residuo("Lata", "Alunimio");
        
        pila.apilar(residuo1);
        pila.apilar(residuo2);
        pila.apilar(residuo3);
        pila.apilar(residuo4);
        
        pila.pasarDatosACola(cola);
        
        System.out.println("Se transladaron los residuos");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        Pila pila = new Pila();
        Cola cola = new Cola();
        
        residuo residuo1 = new residuo("Botella", "Plastico");
        residuo residuo2 = new residuo("Caja", "Carton");
        residuo residuo3 = new residuo("Bolsa", "Plastico");
        residuo residuo4 = new residuo("Lata", "Alunimio");
        
        pila.apilar(residuo1);
        pila.apilar(residuo2);
        pila.apilar(residuo3);
        pila.apilar(residuo4);
        
        pila.pasarDatosACola(cola);
         
        System.out.println(cola.imprimirCola());
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        ListaSimple l = new ListaSimple();
        
        
        ProductoReciclado producto1 = new ProductoReciclado(1, "Anteojos", "Plastico", "1001", "2024-03-31");
        ProductoReciclado producto2 = new ProductoReciclado(2, "Tenedor", "Metal", "1002", "2024-03-31");
        ProductoReciclado producto3 = new ProductoReciclado(3, "LLanta", "Hule", "1003", "2024-03-31");
        ProductoReciclado producto4 = new ProductoReciclado(3, "Martillo", "Metal", "1004", "2024-03-31");
        

        l.insertar(producto1);
        l.insertar(producto2);
        l.insertar(producto3);
        l.insertar(producto4);

        System.out.println(l);
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Pila pila = new Pila();
        Cola cola = new Cola();
        
        residuo residuo1 = new residuo("Botella", "Plastico");
        residuo residuo2 = new residuo("Caja", "Carton");
        residuo residuo3 = new residuo("Bolsa", "Plastico");
        residuo residuo4 = new residuo("Lata", "Alunimio");
        
        pila.apilar(residuo1);
        pila.apilar(residuo2);
        pila.apilar(residuo3);
        pila.apilar(residuo4);
        
        pila.pasarDatosACola(cola);
         
        System.out.println(cola.imprimirCola());
        
        System.out.println(cola.desencolar());
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ListaSimple l = new ListaSimple();
        ListaSimpleCircular LSC = new ListaSimpleCircular();
        
        ProductoReciclado producto1 = new ProductoReciclado(1, "Anteojos", "Platico", "1001", "2024-03-31");
        ProductoReciclado producto2 = new ProductoReciclado(2, "Tenedor", "Metal", "1002", "2024-03-31");
        ProductoReciclado producto3 = new ProductoReciclado(3, "LLanta", "Hule", "1003", "2024-03-31");
        ProductoReciclado producto4 = new ProductoReciclado(4, "Martillo", "Metal", "1004", "2024-03-31");

        l.insertar(producto1);
        l.insertar(producto2);
        l.insertar(producto3);
        l.insertar(producto4);
        
        System.out.println(l.toString());
        
       
        System.out.println(LSC.toString());
        
        LSC.empacar(l);
        
        System.out.println(LSC.toString());
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
